.TH "src Directory Reference" 3 "Wed Jan 10 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBappwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBappwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBbasicevent\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbasicevent\&.h\fP"
.br
.ti -1c
.RI "file \fBbasiceventwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbasiceventwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBcalendar\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcalendar\&.h\fP"
.br
.ti -1c
.RI "file \fBclient\&.cpp\fP"
.br
.ti -1c
.RI "file \fBclient\&.h\fP"
.br
.ti -1c
.RI "file \fBevent\&.cpp\fP"
.br
.ti -1c
.RI "file \fBevent\&.h\fP"
.br
.ti -1c
.RI "file \fBeventwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeventwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBnotifications\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnotifications\&.h\fP"
.br
.ti -1c
.RI "file \fBnotificationswindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnotificationswindow\&.h\fP"
.br
.ti -1c
.RI "file \fBresponsewindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBresponsewindow\&.h\fP"
.br
.ti -1c
.RI "file \fBsaveload\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsaveload\&.h\fP"
.br
.ti -1c
.RI "file \fBscheduler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBscheduler\&.h\fP"
.br
.ti -1c
.RI "file \fBsettings\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsettings\&.h\fP"
.br
.ti -1c
.RI "file \fBsettingswindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsettingswindow\&.h\fP"
.br
.ti -1c
.RI "file \fBsyncdeniedwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsyncdeniedwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBsyncrequestwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBsyncresponsewindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsyncresponsewindow\&.h\fP"
.br
.ti -1c
.RI "file \fBsyncwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsyncwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBtask\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask\&.h\fP"
.br
.ti -1c
.RI "file \fBtoDoList\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtoDoList\&.h\fP"
.br
.ti -1c
.RI "file \fBuser\&.cpp\fP"
.br
.ti -1c
.RI "file \fBuser\&.h\fP"
.br
.in -1c
