.TH "src/appwindow.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/appwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'appwindow\&.h'\fP
.br
\fR#include 'qlistwidget\&.h'\fP
.br
\fR#include 'ui_appwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
