.TH "src/appwindow.h" 3 "Tue Jan 9 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/appwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QPixmap>\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'eventwindow\&.h'\fP
.br
\fC#include 'qlistwidget\&.h'\fP
.br
\fC#include 'responsewindow\&.h'\fP
.br
\fC#include 'settingswindow\&.h'\fP
.br
\fC#include 'syncwindow\&.h'\fP
.br
\fC#include 'basiceventwindow\&.h'\fP
.br
\fC#include 'user\&.h'\fP
.br
\fC#include 'toDoList\&.h'\fP
.br
\fC#include 'notifications\&.h'\fP
.br
\fC#include 'syncdeniedwindow\&.h'\fP
.br
\fC#include 'syncresponsewindow\&.h'\fP
.br
\fC#include 'ui_settingswindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAppWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
