.TH "src/basiceventwindow.cpp" 3 "Tue Jan 9 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/basiceventwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'basiceventwindow\&.h'\fP
.br
\fC#include 'ui_basiceventwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
