.TH "src/client.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/client.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'client\&.h'\fP
.br
\fR#include 'event\&.h'\fP
.br
\fR#include <QCoreApplication>\fP
.br
\fR#include <QEventLoop>\fP
.br
\fR#include <QJsonDocument>\fP
.br
\fR#include <QJsonObject>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
