.TH "src/client.cpp" 3 "Wed Jan 10 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/client.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'client\&.h'\fP
.br
\fC#include 'event\&.h'\fP
.br
\fC#include <QEventLoop>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QCoreApplication>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
