.TH "src/eventwindow.h" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/eventwindow.h
.SH SYNOPSIS
.br
.PP
\fR#include 'calendar\&.h'\fP
.br
\fR#include <QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
