.TH "kOrganizify/src/eventwindow.cpp" 3 "Mon Jan 8 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kOrganizify/src/eventwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'event\&.h'\fP
.br
\fC#include 'eventwindow\&.h'\fP
.br
\fC#include 'ui_eventwindow\&.h'\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QKeyEvent>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
