.TH "src/event.h" 3 "Tue Jan 9 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/event.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QHash>\fP
.br
\fC#include <QObject>\fP
.br
\fC#include 'basicevent\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEvent\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCustomEventPriority\fP { \fBNoPriority\fP, \fBLow\fP, \fBMedium\fP, \fBHigh\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QString \fBcustomEventPriorityToString\fP (\fBCustomEventPriority\fP priority)"
.br
.ti -1c
.RI "\fBCustomEventPriority\fP \fBcustomEventPriorityFromString\fP (const QString &priorityString)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCustomEventPriority\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINoPriority \fP\fP
.TP
\fB\fILow \fP\fP
.TP
\fB\fIMedium \fP\fP
.TP
\fB\fIHigh \fP\fP
.SH "Function Documentation"
.PP 
.SS "\fBCustomEventPriority\fP customEventPriorityFromString (const QString & priorityString)"

.SS "QString customEventPriorityToString (\fBCustomEventPriority\fP priority)"

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
