.TH "src/notificationswindow.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/notificationswindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'notificationswindow\&.h'\fP
.br
\fR#include 'ui_notificationswindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
