.TH "src/saveload.cpp" 3 "Wed Jan 10 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/saveload.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'saveload\&.h'\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QIODevice>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QCoreApplication>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
