.TH "kOrganizify/src/saveload.h" 3 "Mon Jan 8 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kOrganizify/src/saveload.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QJsonObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSaveLoad\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
