.TH "src/saveload.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/saveload.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'saveload\&.h'\fP
.br
\fR#include <QCoreApplication>\fP
.br
\fR#include <QDir>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QIODevice>\fP
.br
\fR#include <QJsonDocument>\fP
.br
\fR#include <QTextStream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
