.TH "src/settingswindow.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settingswindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'settingswindow\&.h'\fP
.br
\fR#include 'ui_settingswindow\&.h'\fP
.br
\fR#include <QDir>\fP
.br
\fR#include <QMap>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
