.TH "src/settings.h" 3 "Wed Jan 10 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settings.h
.SH SYNOPSIS
.br
.PP
\fC#include 'saveload\&.h'\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QJsonValue>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
