.TH "src/settingswindow.h" 3 "Tue Jan 9 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/settingswindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QPalette>\fP
.br
\fC#include <QMap>\fP
.br
\fC#include 'settings\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettingsWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
