.TH "src/syncdeniedwindow.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syncdeniedwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'syncdeniedwindow\&.h'\fP
.br
\fR#include 'ui_syncdeniedwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
