.TH "src/syncresponsewindow.cpp" 3 "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syncresponsewindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'syncresponsewindow\&.h'\fP
.br
\fR#include 'ui_syncresponsewindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
