.TH "Task" 3 "Mon Jan 8 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Task
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTask\fP ()"
.br
.ti -1c
.RI "\fBTask\fP (QString name)"
.br
.ti -1c
.RI "QString \fBgetName\fP () const"
.br
.ti -1c
.RI "void \fBsetName\fP (const QString newName)"
.br
.ti -1c
.RI "bool \fBgetIsChecked\fP () const"
.br
.ti -1c
.RI "void \fBsetIsChecked\fP (const bool isChecked)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QString \fBm_name\fP"
.br
.ti -1c
.RI "bool \fBm_isChecked\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Task::Task ()"

.SS "Task::Task (QString name)"

.SH "Member Function Documentation"
.PP 
.SS "bool Task::getIsChecked () const"

.SS "QString Task::getName () const"

.SS "void Task::setIsChecked (const bool isChecked)"

.SS "void Task::setName (const QString newName)"

.SH "Member Data Documentation"
.PP 
.SS "bool Task::m_isChecked\fC [private]\fP"

.SS "QString Task::m_name\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
