.TH "src/toDoList.h" 3 "Tue Jan 9 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/toDoList.h
.SH SYNOPSIS
.br
.PP
\fC#include 'task\&.h'\fP
.br
\fC#include 'saveload\&.h'\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QVector>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QJsonArray>\fP
.br
\fC#include <QJsonValue>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBToDoList\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
