.TH "src/event.cpp" 3 "Thu Jan 11 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/event.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'event\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "auto \fBcustomEventPriorityToString\fP (\fBCustomEventPriority\fP priority) \-> QString"
.br
.ti -1c
.RI "auto \fBcustomEventPriorityFromString\fP (const QString &priorityString) \-> \fBCustomEventPriority\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "auto customEventPriorityFromString (const QString & priorityString) \-> \fBCustomEventPriority\fP "

.SS "auto customEventPriorityToString (\fBCustomEventPriority\fP priority) \-> QString "

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
