.TH "src/notifications.h" 3 "Thu Jan 11 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/notifications.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QDateTime>\fP
.br
\fC#include <QTimer>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <QList>\fP
.br
\fC#include 'calendar\&.h'\fP
.br
\fC#include 'notificationswindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNotifications\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
