.TH "src/syncwindow.cpp" 3 "Thu Jan 11 2024" "kOrganizify" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/syncwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'syncwindow\&.h'\fP
.br
\fC#include 'settingswindow\&.h'\fP
.br
\fC#include 'ui_syncwindow\&.h'\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for kOrganizify from the source code\&.
